export const acneCausingIngredients = [
  "1-Acetoxyhexadecane",
  "1-Hexadecanol Acetate",
  "Acetylated Lanolin Alcohol",
  "Acetylated Wool Fat",
  "Acetylated Wool Wax",
  "Agar",
  "Ahnfeltia Concinna",
  "Ahnfeltiopsis Concinna Extract",
  "Alaria Esculenta",
  "Alaria Esculenta Extract",
  "Algae",
  "Algae Bladderwrack",
  "Algae Extract",
  "Algea",
  "Algin",
  "Alginate",
  "Alginic Acid",
  "Almond Oil",
  "Andiroba Seed Oil",
  "Aphanothece Sacrum Polysaccharide",
  "Apricot Kernel Oil",
  "Apricot Oil",
  "Arthrospira Platensis",
  "Ascophyllum",
  "Ascophyllum Nodosum",
  "Ascophyllum Nodosum Extract",
  "Asparagopsis Armata Extract",
  "Astrocaryum Murumuru Seed Butter",
  "Avocado Butter",
  "Avokado Oil",
  "Babassu Oil",
  "Beef Tallow",
  "Bismuth",
  "Bismuth Oxychloride",
  "Black Kelp",
  "Bladderwrack",
  "Blue Algae",
  "Blue Green Algae",
  "Borage Oil",
  "Brazil Nut Oil",
  "Brown Algae",
  "Bryopsis Africana",
  "Buriti Oil",
  "Butyl Stearate",
  "Butyl Stearic Acid",
  "Butyrospermum",
  "Butyrospermum Parkii",
  "Cacao Butter",
  "Cacao Seed Butter",
  "Canola Oil",
  "Capea Biruncinata var. Desnuda Sonder",
  "Carageenan",
  "Caragenan",
  "Carastay C",
  "Carrageenan",
  "Carrageenan Gum",
  "Carrageenan Moss",
  "Carragenan",
  "Carrot Seed Oil",
  "Caulerpa Filiformis",
  "Caulerpa Lentillifera Extract",
  "CeraVe Oil",
  "Cetyl Acetate",
  "Chaetomorpha Linum",
  "Cherry Seed Oil",
  "Chlamydomonas Reinhardtii Extract",
  "Chlorella",
  "Chlorophyceae",
  "Chondrus Crispus",
  "Chondrus Crispus Powder",
  "Chullu Seed Oil",
  "Cladophora cf. Subsimplex",
  "Cladophora Radiosa",
  "Cladosiphon Okamuranus Extract",
  "Coal Tar",
  "Cocoa Seed Butter",
  "Coconut",
  "Coconut Alkanes",
  "Coconut Butter",
  "Coconut Extract",
  "Coconut Fruit Extract",
  "Coconut Nucifera Extract",
  "Cocos",
  "Cocos Nucifera",
  "Cocos Nucifera Seed Butter",
  "Codium Fragile Extract",
  "Coenochloris Signiensis Extract",
  "Colloidal Sulfur",
  "Corallina Officinalis Extract",
  "Corn Oil",
  "Cotton Awws",
  "Cotton Awws Oil",
  "Cotton Oil",
  "Cotton Seed Oil",
  "Cranberry Seed Oil",
  "Creosote",
  "Cystoseira Tamariscifolia Extract",
  "D&C Red 17",
  "D&C Red 21",
  "D&C Red 3",
  "D&C Red 30",
  "D&C Red 36",
  "Decyl Oleate",
  "Dictyopteris Membranacea",
  "Dictyopteris Polypodioides",
  "Dilsea Carnosa Extract",
  "Dioctyl Succinate",
  "Disodium Laureth Sulfosuccinate",
  "Disodium Monooleamido",
  "Disodium Monooleamido PEG-2 Sulfosuccinate",
  "Disodium Oleamido PEG-2 Sulfosuccinate",
  "Dodecanoic Acid",
  "Dodecoic Acid",
  "Dodecyl Acid",
  "Dulse",
  "Dunaliella Salina Extract",
  "Duodecylic Acid",
  "Durvillaea Antarctica Extract",
  "Ecklonia",
  "Ecklonia Cava",
  "Ecklonia Cava Extract",
  "Ecklonia Radiata",
  "Enteromorpha Compressa",
  "Enteromorpha Compressa Extract",
  "Ethoxylated Lanolin",
  "Ethylhexyl Palmitate",
  "Ethylhexyl Stearate",
  "Eucheuma Spinosum Extract",
  "Evening Primrose Oil",
  "Flax Oil",
  "Flaxseed Oil",
  "Fucoxanthin",
  "Fucus Serratus",
  "Fucus Vesiculosus",
  "Gamtae Extract",
  "Gelidiella Acerosa Extract",
  "Gelidium Amansii Extract",
  "Gigartina Stellata Extract",
  "Glyceryl 3 Diisostearate",
  "Glyceryl-3 Diisostearate",
  "Glycine Max",
  "Glycine Soja Oil",
  "Gracilariopsis Chorda Extract",
  "Haematococcus Pluvialis",
  "Haematococcus Pluvialis Extract",
  "Haslea Ostrearia",
  "Haslea Ostrearia Extract",
  "Hexadecanol Acetate",
  "Hexadecyl Alcohol",
  "Himanthalia Elongata",
  "Himanthalia Elongata Extract",
  "Hizikia Fusiforme Extract",
  "Hydrogenated Castor Oil",
  "Hydrogenated Vegetable Oil",
  "Hydrolyzed Rhodophyceae Extract",
  "Hypnaceae Extract",
  "Hypnea Musciformis Extract",
  "Irish Moss",
  "Isocetyl Alcohol",
  "Isocetyl Stearate",
  "Isodecyl Oleate",
  "Isooctadecyl Isooctadecanoate",
  "Isopalmitic Alcohol",
  "Isopalmityl Alcohol",
  "Isopropyl Isodecanoate",
  "Isopropyl Isostearate",
  "Isopropyl Lanolate",
  "Isopropyl Linoleate",
  "Isostearyl Isostearate",
  "Isostearyl Neopentanoate",
  "Jania Rubens Extract",
  "Jojoba Butter",
  "Kapok Oil",
  "Kappaphycus",
  "Kappaphycus Alvarezii Extract",
  "Karite",
  "Kelp",
  "Laminaria",
  "Laminaria Digitata",
  "Laminaria Digitata Extract",
  "Laminaria Longicruris",
  "Laminaria Saccharina",
  "Laminaria Saccharina Extract",
  "Lanolic Acid",
  "Lanolin Acetate",
  "Lanolin Alcohol",
  "Lanolin Polyoxyethylene Ether",
  "Laureth 23",
  "Laureth 4",
  "Laureth-23",
  "Laureth-4",
  "Lauric Acid",
  "Laurostearic Acid",
  "Lauryl Sulfate",
  "Linolate",
  "Linseed",
  "Linseed Oil",
  "Linum Usitatissimum Seed Oil",
  "Liquor Picis Carbonis",
  "Lithothamnium Calcareum",
  "Lithothamnium Calcareum Powder",
  "Lola Implexa",
  "Macroalgae",
  "Macrocystis Pyrifera Extract",
  "Magnesium Myristate",
  "Mahua Seed Oil",
  "Marine Algae",
  "Marula",
  "Marula Oil",
  "Mastocarpus",
  "Mastocarpus Stellatus",
  "Microcystis Aeruginosa",
  "Mink Oil",
  "Monostearate",
  "Moringa Oil",
  "Moringa Oleifera Seed Oil",
  "Moss",
  "Myreth-3 Myristate",
  "Myristate",
  "Myristic Acid",
  "Myristyl",
  "Myristyl Alcohol",
  "Myristyl Lactate",
  "Myristyl Propianate",
  "Myristyl Propionate",
  "N-hexadecyl Ethanoate",
  "Norwegian Kelp",
  "Octadecyl Heptanoate",
  "Olea Europaea Fruit Oil",
  "Oleth 3",
  "Oleth-3",
  "Olive Butter",
  "Olive Oil Peg-7 Esters",
  "Padina Pavonica",
  "Palash Oil",
  "Palm Butter",
  "Palm Kernel Oil",
  "Palm Oil",
  "Palmaria Palmata",
  "Palmaria palmata Extract",
  "Palmitic Acid",
  "Palmityl Acetate",
  "Palmityl Alcohol",
  "Papaya Seed Oil",
  "Parkii",
  "Parkii Butter",
  "Parkii Oil",
  "Peanut Oil",
  "PEG 16 Lanolin",
  "PEG-16 Lanolin",
  "PEG-40 Hydrogenated Castor Oil",
  "Pelvetia Canaliculata Extract",
  "Pequot Oil",
  "PG Monostearate",
  "Phaeodactylum Tricornutum Extract",
  "Phaeophyceae",
  "Phytessence Wakame",
  "Pilu Oil",
  "Pine Nut Oil",
  "Plankton",
  "Plankton Extract",
  "Polyglyceryl-Diisostearate",
  "Polysiphonia Elongata Extract",
  "Porphyra",
  "Porphyra Umbilicalis",
  "Porphyridium",
  "Porphyridium Cruentum",
  "Porphyridium Cruentum Extract",
  "Potassium Chloride",
  "Pouteria Sapota Seed Butter",
  "PPG 2 Myristyl Ether Propionate",
  "PPG 2 Myristyl Propionate",
  "PPG-2 Myristyl",
  "PPG-2 Myristyl Propionate",
  "Propylene Glycol Monostearate",
  "Pyrene Coal Tar Pitch",
  "Rapeseed Oil",
  "Red Algae",
  "Red Palm Oil",
  "Rhodophyceae Extract",
  "Rhodophyta",
  "Rockweed",
  "Sargassum",
  "Sargassum Filipendula Extract",
  "Sargassum Fusiforme Extract",
  "Sclerocarya Birrea",
  "Sclerocarya Birrea Seed Oil",
  "Sea Fern",
  "Sea Grass",
  "Seaweed",
  "Sesame Oil",
  "Sesame Seed",
  "Sesamum Indicum",
  "Shark Liver Oil",
  "Shark Squalene",
  "Shea",
  "Shea Nut Oil",
  "Sheep Alcohol",
  "SLES",
  "SLO",
  "SLS",
  "Sodium Alginate",
  "Sodium Dodecyl Sulfate",
  "Sodium Laureth Sulfate",
  "Sodium Lauryl Ether Sulfate",
  "Sodium Lauryl Sulfate",
  "Soja",
  "Solulan 16",
  "Sorbitan Oleate",
  "Soy",
  "Soybean",
  "Soybean Oil",
  "Sphacelaria",
  "Spirulina",
  "Squalene",
  "Steareth 10",
  "Steareth-10",
  "Stearic Acid Tea",
  "Stearyl Heptanoate",
  "Sulfated Castor Oil",
  "Sulfated Jojoba Oil",
  "Sunflower Butter",
  "Sweet Almond Butter",
  "Sweet Almond Oil",
  "Tallow",
  "Tetradecyl Myristate",
  "Theobroma Butter",
  "Theobroma Cocoa Seed Butter",
  "Theobroma Oil",
  "Triticum Aestivum",
  "Triticum Vulgare",
  "Tucuma Butter",
  "Turkey Red Oil",
  "Ulva Fasciata",
  "Ulva Lactuca",
  "Ulva Rhacodes",
  "Undaria",
  "Undaria Pinnatifida",
  "Vitamin E Oil",
  "Vitellaria paradoxa",
  "Wakame",
  "Wheat Germ Glyceride",
  "Wheat Germ Oil",
  "Wool Alcohol",
  "Wool Fat",
  "Xanthophyta",
  "Xylene",
  "Zea Mays (Corn) Oil",
];

export function normalizeIngredient(ingredient: string): string {
  return ingredient
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s]/g, ' ') // Replace all non-alphanumeric (including hyphens) with spaces
    .replace(/\s+/g, ' ') // Normalize multiple spaces
    .trim();
}

export function checkIngredients(inputText: string): {
  foundIngredients: string[];
  safeIngredients: string[];
  totalChecked: number;
} {
  const lines = inputText
    .split(/[,\n]/)
    .map(line => line.trim())
    .filter(line => line.length > 0);

  const normalizedAcneCausingIngredients = acneCausingIngredients.map(normalizeIngredient);
  
  const foundIngredients: string[] = [];
  const safeIngredients: string[] = [];

  lines.forEach(line => {
    const normalizedLine = normalizeIngredient(line);
    
    // Split the input ingredient into words for word-boundary matching
    const inputWords = normalizedLine.split(/\s+/).filter(w => w.length > 0);
    
    // Check if the ingredient matches any acne-causing ingredient
    const isAcneCausing = normalizedAcneCausingIngredients.some(acneIngredient => {
      // Split acne-causing ingredient into words
      const acneWords = acneIngredient.split(/\s+/).filter(w => w.length > 0);
      
      // Exact match - entire ingredient matches
      if (normalizedLine === acneIngredient) return true;
      
      // Word-level matching with EXACT word equality only
      // Check if all words from the acne ingredient exist as complete words in the input
      const allAcneWordsInInput = acneWords.every(acneWord => 
        inputWords.includes(acneWord)
      );
      
      // If all words from acne ingredient are present as exact words, it's a match
      return allAcneWordsInInput && acneWords.length > 0;
    });
    
    if (isAcneCausing) {
      foundIngredients.push(line);
    } else if (normalizedLine) {
      safeIngredients.push(line);
    }
  });

  return {
    foundIngredients,
    safeIngredients,
    totalChecked: lines.length,
  };
}
